Patch 1
kpcyrd/mini-docker-rust pull request #8
Opened 2022-01-09 07:30 UTC by parasew

This patch has two small updates:

1. Update to a easier to read Rust version number (from rust:1-alpine3.13 to 1.57-alpine)
2. Updated Rust to 1.57
3. Alpine Linux 3.15 update

With the changes, the container size is 6.01MB.

2022-01-09 16:05 UTC, kpcyrd requested changes
Thanks for your PR, I've added two comments. I'm going to merge this after they're fixed. :)

2022-01-09 16:05 UTC, kpcyrd commented on Dockerfile
> +FROM rust:1.57-alpine
```suggestion
FROM rust:1-alpine3.14
```
This should pin a specific alpine release, but pinning a rust compiler version is not necessary.

2022-01-09 16:05 UTC, kpcyrd commented on Dockerfile
> +FROM alpine:3.15
```suggestion
FROM alpine:3.14
```
The latest rust docker image is still on 3.14.

2022-01-10 04:00 UTC, parasew commented
Hi, the changes you mentioned have been implemented. I am monitoring to check when 3.15 packages are on docker hub and will make sure this repo is always up to date in the future. For now I think it is safe to merge :)

2022-01-10 04:02 UTC, kpcyrd approved these changes

2022-01-10 04:02 UTC, merged

2022-01-10 04:02 UTC, kpcyrd commented
Thanks! :heart: